import TaskDTO from "../dto/TaskDTO";
import ITask from "../model/ITask";

export default class Task implements ITask {
  private readonly _taskId: string;
  private _title: string;
  private _maxPoints: number;
  private readonly _ccId: number;
  private _linkCcId: number | null;

  constructor(taskId: string, title: string, maxPoints: number, ccId: number, linkCcId: number | null) {
    this._taskId = taskId;
    this._title = title;
    this._maxPoints = maxPoints;
    this._ccId = ccId;
    this._linkCcId = linkCcId;
  }

  get taskId(): string {
    return this._taskId;
  }

  get title(): string {
    return this._title;
  }

  get maxPoints(): number {
    return this._maxPoints;
  }

  get ccId(): number {
    return this._ccId;
  }

  equals(other: unknown): boolean {
    if (other == null) {
      return false;
    }
    if (this === other) {
      return true;
    }
    if (typeof this !== typeof other) {
      return this == other;
    }
    return this._taskId === (other as Task).taskId;
  }

  assembleDTO(): TaskDTO {
    return new TaskDTO(this._taskId, this._title, this._maxPoints);
  }

  async jumpTo(context: Word.RequestContext): Promise<void> {
    const contentControl = this.getAssociatedContentControl(context);
    const range = contentControl.getRange(Word.RangeLocation.whole);
    range.select(Word.SelectionMode.select);

    await context.sync();
  }

  jumpToAsync(): Promise<void> {
    return Word.run(async (context) => this.jumpTo(context));
  }

  editAsync(fieldName: string, newValue: string): Promise<void> {
    return Word.run(async (context) => this.edit(context, fieldName, newValue));
  }

  async edit(context: Word.RequestContext, fieldName: string, newValue: string | number): Promise<void> {
    switch (fieldName) {
      case "title": {
        this._title = newValue as string;
        const contentControl = this.getAssociatedContentControl(context);
        contentControl.title = newValue.toString();
        break;
      }
      case "maxPoints": {
        this._maxPoints = newValue as number;
        break;
      }
      default:
        console.warn(`Unknown task field: ${fieldName}`);
    }

    await context.sync();
  }

  async prepareForDeletionAsync() {
    return Word.run(async (context) => this.prepareForDeletion(context));
  }

  async prepareForDeletion(context: Word.RequestContext) {
    // delete associated content control
    const contentControl = this.getAssociatedContentControl(context);

    // keep content
    contentControl.delete(true);

    await context.sync();
  }

  getAssociatedContentControlAsync(): Promise<Word.ContentControl | null> {
    return Word.run(async (context) => this.getAssociatedContentControl(context));
  }

  getAssociatedContentControl(context: Word.RequestContext): Word.ContentControl | null {
    return context.document.contentControls.getByIdOrNullObject(this._ccId);
  }

  getLInkContentControlAsync(): Promise<Word.ContentControl | null> {
    return Word.run(async (context) => this.getLinkContentControl(context));
  }

  getLinkContentControl(context: Word.RequestContext): Word.ContentControl | null {
    return context.document.contentControls.getByIdOrNullObject(this._linkCcId);
  }

  async removeLinkContentControl(context: Word.RequestContext): Promise<void> {
    if (this._linkCcId != null) {
      const linkContentControl = this.getLinkContentControl(context);
      if (linkContentControl == null) {
        console.warn(`Link content control with id ${this._linkCcId} does not exist`);
      } else {
        // Delete with content
        linkContentControl.delete(false);

        await context.sync();
      }
    }
  }

  async insertLinkContentControl(context: Word.RequestContext): Promise<void> {
    const contentControl = this.getAssociatedContentControl(context);

    if (contentControl == null) {
      console.error(`Task content control with id ${this._ccId} does not exist`);
      return;
    }

    const linkContentControl = contentControl.getRange(Word.RangeLocation.start).insertContentControl();

    linkContentControl.appearance = Word.ContentControlAppearance.hidden;
    linkContentControl.tag = "task-link";
    linkContentControl.title = "task-link-" + this._taskId;

    /*
     Insert anchor element.
     Hyperlinks emerged as the best alternative to create markers inside the PDF document generated by Word.
     Bookmarks, although preferable, are not exported properly.
     */
    linkContentControl.insertHtml(
      `<a style="text-decoration: none; font-size:0.01em; transform: translate(-1px)" href="task-${this._taskId}">&nbsp;</a>`,
      Word.InsertLocation.start
    );

    linkContentControl.load("id");

    await context.sync();

    this._linkCcId = linkContentControl.id;
  }
}
